# Generated by Django 4.1.3 on 2022-11-26 15:50

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='countries',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
