# Generated by Django 4.1.3 on 2022-12-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_billing_address_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a sample description'),
        ),
    ]
